Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,20 +10,19 @@ jobs:
         SOURCE: ${{ github.head_ref }}
         TARGET: ${{ github.base_ref }}
       steps:
-        - run:
-            echo "DEBUG::SOURCE is $SOURCE & TARGET is $TARGET"
+        - run: echo "DEBUG::SOURCE is $SOURCE & TARGET is $TARGET";
             
-            if [[ "$TARGET" != @(main|staging|develop|pre_develop) ]]; then echo "error:The target branch can not equal {${TARGET}}" && exit 1; fi;
+        - run: if [[ "$TARGET" != @(main|staging|develop|pre_develop) ]]; then echo "error:The target branch can not equal {${TARGET}}" && exit 1; fi;
             
-            if [ "$SOURCE" == "main" ]; then echo "error:SOURCE branch can not equal to {main}" && exit 1; fi;
+        - run: if [ "$SOURCE" == "main" ]; then echo "error:SOURCE branch can not equal to {main}" && exit 1; fi;
            
-            if [[ "$SOURCE" != @(main|staging|develop|pre_develop) ]] && [ "$TARGET" != "pre_develop" ]; then echo "error:The branch {${SOURCE}} need to merge with pre_develop first." && exit 1; fi;
+        - run: if [[ "$SOURCE" != @(main|staging|develop|pre_develop) ]] && [ "$TARGET" != "pre_develop" ]; then echo "error:The branch {${SOURCE}} need to merge with pre_develop first." && exit 1; fi;
            
-            if [ "${SOURCE}" == 'pre_develop' ] && [[ "$TARGET" != @(develop|staging) ]]; then echo "error:The branch {${SOURCE}} should target to {develop|staging}" && exit 1; fi;
+        - run: if [ "${SOURCE}" == 'pre_develop' ] && [[ "$TARGET" != @(develop|staging) ]]; then echo "error:The branch {${SOURCE}} should target to {develop|staging}" && exit 1; fi;
           
-            if [ "${SOURCE}" == 'develop' ] && [[ "$TARGET" != @(staging|main) ]]; then echo "error:The branch {${SOURCE}} should target to {staging|main}" && exit 1; fi;
+        - run: if [ "${SOURCE}" == 'develop' ] && [[ "$TARGET" != @(staging|main) ]]; then echo "error:The branch {${SOURCE}} should target to {staging|main}" && exit 1; fi;
           
-            if [ "${SOURCE}" == 'staging' ] && [[ "$TARGET" != "main" ]]; then echo "error:The branch {${SOURCE}} should target to {main}" && exit 1; fi;
+        - run: if [ "${SOURCE}" == 'staging' ] && [[ "$TARGET" != "main" ]]; then echo "error:The branch {${SOURCE}} should target to {main}" && exit 1; fi;
 
   # job1:
   #   runs-on: ubuntu-latest
